# Generated by Django 4.1.3 on 2022-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
