# Generated by Django 4.1.3 on 2022-11-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference_v2', '0002_presentation_content_presentation_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_Name', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('presentation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference_v2.presentation')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference_v2.room')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
